name: Lint JavaScript

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              # v4.2.2
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af6838
              with:
                  fetch-depth: 0

            - name: Add build cache
              # v4
              uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Setup Node
              # v4
              uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e
              with:
                  node-version-file: '.nvmrc'

            - name: Install node packages
              uses: nick-fields/retry@7c68161adf97a48beb850a595b8784ec57a98cbb
              with:
                  timeout_minutes: 10
                  max_attempts: 5
                  command: npm ci

            - name: Lint with ESLint
              run: npx eslint --max-warnings=0 $(git diff --diff-filter=ACM --name-only origin/main '**/*.js' | xargs)
            - name: Lint for Firefox
              run: npm run lint:firefox

