name: Bump version

on:
  push:
    branches: [main]

jobs:
  version:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'osbotify-app[bot]' }} # prevent infinite loop
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: main

      - name: Generate a GitHub App token
        id: generateAppToken
        uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5 # v2.0.2
        with:
          app-id: ${{ secrets.OS_BOTIFY_APP_ID }}
          private-key: ${{ secrets.OS_BOTIFY_PRIVATE_KEY }}

      - name: Get merged pull request
        id: getMergedPullRequest
        run: |
          echo "ORIGINAL_PR_URL=$(gh pr list --state merged --json 'mergeCommit,url' --jq '.[] | select(.mergeCommit.oid | contains("${{ github.sha }}")) | .url')" >> "$GITHUB_OUTPUT"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # Generates new-version output with the new version number
      - name: Bump version
        id: bump-version
        run: ./tools/bumpVersion.sh >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Created signed commit and push tags
        run: |
          set -euxo pipefail
          readonly VERSION="${{ steps.bump-version.outputs.new-version }}"

          # Push commits for the updated files
          for FILE in package.json package-lock.json assets/manifest.json assets/manifest-firefox.json ; do
            MESSAGE="Update $FILE version to $VERSION"
            SHA=$(git rev-parse "main:$FILE")
            # Create a file with the base64 encoded content
            base64 -i "$FILE" > "base64.txt"
            NEW_COMMIT_SHA=$(gh api --method PUT "/repos/:owner/:repo/contents/$FILE" \
              --field message="$MESSAGE" \
              --field content="@base64.txt" \
              --field encoding="base64" \
              --field branch="main" \
              --field sha="$SHA" \
              --jq '.commit.sha')
          done

          # Set up git user info so we can push a tag
          # osbotify-app[bot] GitHub App ID can be found here: https://api.github.com/users/osbotify-app[bot]
          git config --global user.name "osbotify-app[bot]"
          git config --global user.email infra+osbotify@expensify.com

          # Fetch the commit that was made via the API
          git fetch origin main

          # Tag new_commit_sha with our new version
          git tag -a "$VERSION" "$NEW_COMMIT_SHA" -m "$VERSION"

          # Push the new tag
          git push origin tag "$VERSION"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ steps.generateAppToken.outputs.token }}

      - name: Comment on PR
        run: |
          gh pr comment ${{ steps.getMergedPullRequest.outputs.ORIGINAL_PR_URL }} --body ":rocket: Released in version ${{ steps.bump-version.outputs.new-version }} :rocket:"
        env:
          GH_TOKEN: ${{ steps.generateAppToken.outputs.token }}
        shell: bash
